export const getMovieFixture = () => ({
  adult: false,
  backdrop_path: "/fPGeS6jgdLovQAKunNHX8l0avCy.jpg",
  belongs_to_collection: null,
  budget: 0,
  genres: [
    { id: 28, name: "Action" },
    { id: 12, name: "Adventure" },
    { id: 53, name: "Thriller" },
    { id: 10752, name: "War" },
  ],
  homepage: "https://www.amazon.com/dp/B08VFD1Y3B",
  id: 567189,
  imdb_id: "tt0499097",
  original_language: "en",
  original_title: "Tom Clancy's Without Remorse",
  overview:
    "An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his pregnant wife.",
  popularity: 3047.272,
  poster_path: "/rEm96ib0sPiZBADNKBHKBv5bve9.jpg",
  production_companies: [
    {
      id: 4,
      logo_path: "/fycMZt242LVjagMByZOLUGbCvv3.png",
      name: "Paramount",
      origin_country: "US",
    },
    {
      id: 433,
      logo_path: null,
      name: "Weed Road Pictures",
      origin_country: "US",
    },
    {
      id: 82819,
      logo_path: "/5Z8WWr0Lf1tInVWwJsxPP0uMz9a.png",
      name: "Skydance Media",
      origin_country: "US",
    },
    {
      id: 51593,
      logo_path: null,
      name: "Midnight Radio",
      origin_country: "US",
    },
    {
      id: 102334,
      logo_path: "/espa8KYmHedu5p7GRrP9FFICLUp.png",
      name: "Outlier Society Productions",
      origin_country: "US",
    },
    {
      id: 114732,
      logo_path: "/tNCbisMxO5mX2X2bOQxHHQZVYnT.png",
      name: "New Republic Pictures",
      origin_country: "US",
    },
    {
      id: 20580,
      logo_path: "/tkFE81jJIqiFYPP8Tho57MXRQEx.png",
      name: "Amazon Studios",
      origin_country: "US",
    },
  ],
  production_countries: [
    { iso_3166_1: "US", name: "United States of America" },
  ],
  release_date: "2021-04-29",
  revenue: 0,
  runtime: 109,
  spoken_languages: [
    { english_name: "English", iso_639_1: "en", name: "English" },
  ],
  status: "Released",
  tagline: "",
  title: "Tom Clancy's Without Remorse",
  video: false,
  vote_average: 7.3,
  vote_count: 695,
});

export const getMovieListFixture = () => ({
  page: 1,
  results: [...new Array(20)].map(() => ({
    adult: false,
    backdrop_path: "/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg",
    genre_ids: [28, 12, 14, 878],
    id: 299536,
    original_language: "en",
    original_title: "Avengers: Infinity War",
    overview:
      "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
    poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    release_date: "2018-04-25",
    title: "Avengers: Infinity War",
    video: false,
    vote_average: 8.3,
    vote_count: 6937,
    popularity: 358.799,
  })),
  total_pages: 12,
  total_results: 222,
});
